name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        uses: ./.github/actions/test
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
